dialect "java"

import org.optaplanner.core.api.score.buildin.hardsoftlong.HardSoftLongScoreHolder;
import uk.ac.diamond.ss.domain.Allocation;

import org.optaplanner.core.api.score.constraint.primint.IntConstraintMatch;

global HardSoftLongScoreHolder scoreHolder;

rule "sameAllocation"
    when
    	pa1 : Allocation(getShift() != null)
		pa2 : Allocation(ID> pa1.ID, getShift().getID() == pa1.getShift().getID())
    then
    scoreHolder.addHardConstraintMatch(kcontext, -5);
end

rule "differentShifts"
    when
    	pa1 : Allocation(getShift() != null)
		pa2 : Allocation(ID> pa1.ID, getShift().getID() != pa1.getShift().getID())
		pa3 : Allocation(ID> pa2.ID, ID> pa1.ID, getShift().getID() != pa1.getShift().getID(),getShift().getID() != pa2.getShift().getID())
    then
    scoreHolder.addHardConstraintMatch(kcontext, +5);
end
